### ISSUE TITLE
Problem with the Wrapper.

### ISSUE THREAD

**Issue by ItsVinnyX** [derin-n/MCAPIJavaWrapper#1]
POM.XML:
`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>VenomBOT</groupId>
	<artifactId>VenomBOT</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>lib/</classpathPrefix>
							<mainClass>com.venomsurge.VenomBOT</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>jcenter</id>
			<name>jcenter-bintray</name>
			<url>https://jcenter.bintray.com</url>
		</repository>

		<repository>
			<id>central</id>
			<name>bintray</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>net.dv8tion</groupId>
			<artifactId>JDA</artifactId>
			<version>4.1.1_142</version>
		</dependency>

		<dependency>
			<groupId>com.sedmelluq</groupId>
			<artifactId>lavaplayer</artifactId>
			<version>1.3.47</version>
		</dependency>

		<dependency>
			<groupId>javax.json</groupId>
			<artifactId>javax.json-api</artifactId>
			<version>1.1.4</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0.4</version>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.3.0-alpha5</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>`

Code: 
`package com.venomsurge;

import com.venomsurge.handlers.CommandHandler;
import com.venomsurge.listeners.CommandListener;
import com.venomsurge.listeners.MyListener;
import com.venomsurge.minecraft.Server;
import com.venomsurge.music.commands.MusicCommand;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;

public class VenomBOT implements Runnable {

	public static JDA api;

	public void run() {
		while (true) {
			String activity = null;
			Server server = new Server("play.venomsurge.net");

			if (server.isOnline()) {
				if (server.getCurrentPlayers() == 1) {
					activity = "VenomSurge with 1 player.";
				} else {
					activity = "VenomSurge with " + server.getCurrentPlayers() + " players.";
				}
			} else {
				activity = "Server is offline!";
			}
			api.getPresence().setActivity(Activity.playing(activity));
			try {
				Thread.sleep(30000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}

	public static void main(String[] args) throws Exception {
		String activity = null;
		Server server = new Server("play.venomsurge.net");

		if (server.isOnline()) {
			if (server.getCurrentPlayers() == 1) {
				activity = "VenomSurge with 1 player.";
			} else {
				activity = "VenomSurge with " + server.getCurrentPlayers() + " players.";
			}
		} else {
			activity = "Server is offline!";
		}
		api = JDABuilder.createDefault("KEY HERE")
				.setStatus(OnlineStatus.ONLINE).setActivity(Activity.playing(activity))
				.addEventListeners(new MyListener(), new CommandListener()).build();
		CommandHandler.commands.put("m", new MusicCommand());
		CommandHandler.commands.put("music", new MusicCommand());

		// Launch thread to periodically update the status
		new Thread(new VenomBOT()).start();
	}

}`

OUTPUT:
`Exception in thread "main" java.lang.IllegalStateException: read/readObject/readArray/close method is already called
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:97)
	at com.venomsurge.minecraft.Server.isOnline(Server.java:51)
	at com.venomsurge.VenomBOT.main(VenomBOT.java:53)
`

**Comment by derin-n** [comment]
I updated the Server file to include a ServerManager class which you can use to create a Server object like this
`Server server = ServerManager.createServer("play.venomsurge.net");`
And you can use everything else like before but you should check if the server is null just in case something went wrong .

**Comment by ItsVinnyX** [comment]
Thanks!

**Comment by derin-n** [comment]
no problem brother, it's surprising to see someone using this 4 years later after I made it.

**Comment by ItsVinnyX** [comment]
> no problem brother, it's surprising to see someone using this 4 years later after I made it.

Hahaha, my whole discord bot uses this.

**Comment by derin-n** [comment]
glad to know, good luck in the future bro.
